urls.py
from django.urls import path
from .views import (
    KanbanCreateView,
    KanbanListView,
    KanbanDeleteView,
    KanbanDetailView,
    TaskCreateView,
    TaskDeleteView,
    TaskDetailView,
    TaskActivateView,
    TaskCancelView,
    TaskCompleteView,
    LoginView,
    LogoutView,
    SignUpView,
    about,
    tasks_overdue,
    help,
)

app_name = "kanban"

urlpatterns = [
    path("", KanbanListView.as_view(), name="index"),
    path("kanban_create", KanbanCreateView.as_view(), name="kanban_create"),
    path("kanban_delete/<int:pk>", KanbanDeleteView.as_view(), name="kanban_delete"),
    path("kanban_detail/<int:pk>", KanbanDetailView.as_view(), name="kanban_detail"),
    path("task_create/<int:pk>", TaskCreateView.as_view(), name="task_create"),
    path("task_detail/<int:pk>", TaskDetailView.as_view(), name="task_detail"),
    path("task_delete/<int:pk>", TaskDeleteView.as_view(), name="task_delete"),
    path("task_activate/<int:pk>", TaskActivateView.as_view(), name="task_activate"),
    path("task_cancel/<int:pk>", TaskCancelView.as_view(), name="task_cancel"),
    path("task_complete/<int:pk>", TaskCompleteView.as_view(), name="task_complete"),
    path("user_login", LoginView.as_view(), name="user_login"),
    path("user_logout", LogoutView.as_view(), name="user_logout"),
    path("user_register", SignUpView.as_view(), name="user_register"),
    path("about", about, name="about"),
    path("tasks_overdue", tasks_overdue, name="tasks_overdue"),
    path("help", help, name="help"),
]

templates/kanban/about.html
{% extends "kanban/base.html" %}
{% load static %}
{% block content %}

    <section class="about-section">
        <h2 class="section-heading">Команда проекта</h2>
        
        <div class="team-container">
            <article class="team-item">
                <img class="image--responsive team_photo" src="{% static 'img/alexandra-shibaeva.jpg' %}" alt="Александра Шибаева">
                <h3>Александра Шибаева</h3>
                <h4>разработчик</h4>
                <p>бекенд, фронтенд</p>
            </article>

            <article class="team-item">
                <img class="image--responsive team_photo" src="{% static 'img/bogdan-alexandrov.jpg' %}" alt="Богдан Александров">
                <h3>Богдан Александров</h3>
                <h4>тестировщик</h4>
                <p>сценарии, тестирование, презентация</p>
            </article>

            <article class="team-item">
                <img class="image--responsive team_photo" src="{% static 'img/pavel-sidorov.jpg' %}" alt="Павел Сидоров">
                <h3>Павел Сидоров</h3>
                <h4>наставник</h4>
                <p>продукт, деплой</p>
                <a href="https://vk.com/sdrvpvl"><img class="social" src="{% static 'img/vk.svg' %}" alt="вконтактик"></a>
            </article>
        </div>
    </section>

    <section class="about-section">
        <h2 class="section-heading">Идея проекта</h2>
            <p>В 2022–2023 годах многие зарубежные компании прекратили поддержку или ограничили доступ к своим продуктам пользователям из России. У нас не осталось бесплатных аналогов онлайн-приложений для планирования задач – <a href="https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D0%BD%D0%B1%D0%B0%D0%BD_(%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0)">канбанов</a>. Так мы решили сделать свое приложение-канбан, где школьники, студенты и преподаватели могли бы просто и бесплатно планировать работу над небольшими проектами. Сейчас этот инструмент особенно важен для проектной работы.</p>
    </section>

    <section class="about-section">
        <h2 class="section-heading">Цель проекта</h2>
            <p>разработать веб-приложение на <a href="https://www.djangoproject.com/">Django</a> для планирования мелких проектов: постановки задач и контроля их исполнения к 11 июня 2023 года.</p>
    </section>

    <section class="about-section">
        <h2 class="section-heading">Задачи проекта</h2>
        <ol>
            <li>продумать сценарии пользователя канбана;</li>
            <li>реализовать модели канбана;</li>
            <li>реализовать представления канбана;</li>
            <li>реализовать шаблоны канбана;</li>
            <li>протестировать проект на локальном сервере;</li>
            <li>купить домен kanbanka.ru и хостинг под Django;</li>
            <li>сделать деплой проекта на хостинг;</li>
            <li>подготовить презентацию проекта.</li>
        </ol>
    </section>

    <a class="link-button" href="{% url 'kanban:index' %}">на главную</a>


{% endblock %}

templates/kanban/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta property="og:title" content="Канбанка">
    <meta property="og:site_name" content="Канбанка">
    <meta property="og:url" content="https://kanbanka.ru">
    <meta property="og:description" content="Планирование задач онлайн">
    <meta property="og:type" content="website">
    <meta property="og:image" content={% static "img/og.jpg" %}>

    <title>Канбанка: планирование задач</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans:wght@700&family=PT+Serif&display=swap" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/media.css' %}">
</head>
<body style="background-image: url('{% static "img/bg.jpg" %}');">

    <div class="page_container">
        <header class="header-container">

            <nav class="nav-container">
                <ul class="header-list nav-list">
                    <li class="header-list-item">
                        <a class="header-link" href="{% url 'kanban:index' %}">главная страница</a>
                    </li>
                    <li class="header-list-item">
                        <a class="header-link" href="{% url 'kanban:about' %}">о проекте</a>
                    </li>
                    {% if user.is_authenticated %}
                        {% if user.is_staff %}
                            <li class="header-list-item">
                                <a class="header-link" href="{% url 'admin:index' %}">админка</a>
                            </li>
                        {% endif %}
                    {% endif %}
                    <li class="header-list-item">
                        <a class="header-link" href="{% url 'kanban:help' %}">помощь</a>
                    </li>
                </ul>
            </nav>

            <div class="logo-container">
                <a class="logo-item" href="{% url 'kanban:index' %}">
                    <span class="logo-text">Канбанка</span>
                </a>
            </div>

            <div class="user-container">
                <ul class="header-list">
                    {% if user.is_authenticated %}
                    <li class="header-list-item">
                        Привет, <strong>{{ user.username }}</strong>!
                    </li>
                    <li class="header-list-item">
                        <a class="header-link" href="{% url 'kanban:user_logout' %}">выйти</a>
                    </li>
                    {% else %}
                    <li class="header-list-item">
                        <a class="header-link" href="{% url 'kanban:user_login' %}">войти</a>
                    </li>
                    <li class="header-list-item">
                        <a class="header-link" href="{% url 'kanban:user_register' %}">зарегистрироваться</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </header>
        
        <main class="main-container">
            {% block content %}{% endblock %}
        </main>

        <footer class="footer-container">
            <p class="footer-item">&copy; 2023 &ndash; команда &laquo;Свидетели Баго́вы&raquo; и кружок <a class="footer-link" href="https://vk.com/ddtinfo">&laquo;Информационные технологии&raquo;</a></p>
        </footer>

    </div>
    
</body>
</html>

templates/kanban/help.html
{% extends "kanban/base.html" %}
{% load static %}
{% block content %}

    <section class="video-section">
        <h2 class="section-heading">Помощь</h2>
        <iframe style="background-image: url('{% static "img/loading.png" %}');" class="youtube-video" src="https://www.youtube.com/embed/MW-3aMcJM60" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    </section>

    <a class="link-button" href="{% url 'kanban:index' %}">на главную</a>
    
{% endblock %}

templates/kanban/index.html
{% extends "kanban/base.html" %}

{% block content %}
    <div class="index-container">

    
    {% if login_required %}
    <div class="main-item">
        <div class="login_required">
            <h2 class="kanbans-title">Вы кто?</h2>
            <a class="kanbans-link" href="{% url 'kanban:user_login' %}">войдите</a> или 
            <a class="kanbans-link" href="{% url 'kanban:user_register' %}">зарегистрируйтесь</a>
            чтобы увидеть здесь свои доски.
        </div>
    </div>
    {% else %}
        <div class="main-item">
            {% if my_kanbans %}
                <section class="kanbans-section">
                    <h2 class="kanbans-title">мои доски</h2>
                    <ul class="kanbans-list">
                        {% for kanban in my_kanbans %}
                        <li class="kanbans-item">
                            <a class="kanbans-link" href="{% url 'kanban:kanban_detail' kanban.id %}">{{ kanban.name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </section>
                    {% if user.is_authenticated %}
                        <p>
                            <a class="link-button" href="{% url 'kanban:kanban_create' %}">создать доску</a>
                        </p>
                    {% endif %}
            {% else %}
                <h2 class="kanbans-title">мои доски</h2>
                <p>Вы пока не создали досок.</p>
                {% if user.is_authenticated %}
                    <p>
                        <a class="link-button" href="{% url 'kanban:kanban_create' %}">создать доску</a>
                    </p>
                {% endif %}
            {% endif %}
        </div>

        {% if partner_kanbans %}
            <div class="main-item">
            <section class="kanbans-section">
                <h2 class="kanbans-title">доски с задачами для меня</h2>
                <ul class="kanbans-list">
                {% for kanban in partner_kanbans %}
                    <li class="kanbans-item">
                        <a class="kanbans-link" href="{% url 'kanban:kanban_detail' kanban.id %}">{{ kanban.name }}</a>
                    </li>
                {% endfor %}
                </ul>
            </section>
            </div>
        {% endif %}

    {% endif %} 
    </div> 


{% endblock %}

templates/kanban/kanban_create.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="main-item">
    <form class="task-form" action="" method="POST">
        <h2>Создать доску</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-button" type="submit" value="создать доску">
    </form>
    <p>
        <a class="link-button" href="{% url 'kanban:index' %}">на главную</a>
    </p>
</div>
{% endblock %}

templates/kanban/kanban_delete.html
{% extends "kanban/base.html" %}

{% block content %}
    <div class="main-item">
        <form class="task-form" action="" method="POST">
            <h2>Удалить доску</h2>
            <p>Это действие нельзя будет отменить!</p>
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-button button--red" type="submit" value="удалить доску">
        </form>
        <p>
            <a class="link-button" href="{% url 'kanban:index' %}">на главную</a>
        </p>
    </div>
{% endblock %}

templates/kanban/kanban_detail.html
{% extends "kanban/base.html" %}

{% block content %}
 
    <h2 class="kanban-title">{{ kanban.name }}</h2>
    <p class="kanban-owner">хозяин доски: <b>{{ kanban.owner }}</b></p>
    <div class="tasks-container">
        <div class="tasks-item task-new">
            <h3 class="tasks-category-title">новые задачи:</h3>
            <ol class="tasks-list">
            {% for task in tasks_new %}
                <li>
                    <h4>{{ task.name }}</h4>
                    <p class="task-info">
                        <strong>создано:</strong> {{ task.created_date }} в {{ task.created_time }}
                    </p>
                    <p class="task-description">
                        <strong>описание: </strong>{{ task.description|truncatechars:100 }}
                    </p>
                    {% if object.owner == user %}
                    <div class="task-controls">
                        <a class="task-controls-link button--grey" href="{% url 'kanban:task_detail' task.id %}">к&nbsp;задаче</a>
                        <a class="task-controls-link button--yellow" href="{% url 'kanban:task_activate' task.id %}">назначить</a>
                        <a class="task-controls-link button--red" href="{% url 'kanban:task_delete' task.id %}">удалить</a>
                    </div>
                    {% endif %}
                </li>
            
            {% empty %}
                <li>нет новых задач</li>
                {% if object.owner == user %}
                    <li>
                        <a class="task-controls-link button--grey" href="{% url 'kanban:task_create' kanban.id %}">добавить задачу</a>
                    </li>
                {% endif %}    
            {% endfor %}
            </ol>
        </div>

        <div class="tasks-item task-active">
            <h3 class="tasks-category-title">активные задачи:</h3>
            <ol class="tasks-list">
            {% for task in tasks_active %}
                <li>
                    <h4>{{ task.name }}</h4>
                    <p class="task-info">
                        <strong>исполнитель:</strong> {{ task.executor }}<br>
                        <strong>назначено:</strong> {{ task.assigned_date }} в {{ task.assigned_time }}<br>
                        <strong>дедлайн:</strong> {{ task.deadline_date }} в {{ task.deadline_time }}
                    </p>
                    <p class="task-description">
                        <strong>описание:</strong> {{ task.description|truncatechars:100 }}
                    </p>
                    {% if object.owner == user %}
                        <div class="task-controls">
                            <a class="task-controls-link button--grey" href="{% url 'kanban:task_detail' task.id %}">к&nbsp;задаче</a>
                            <a class="task-controls-link button--green" href="{% url 'kanban:task_complete' task.id %}">завершить</a>
                            <a class="task-controls-link button--red" href="{% url 'kanban:task_delete' task.id %}">удалить</a>
                        </div>
                    {% elif task.executor == user %}
                        <div class="task-controls">
                            <a class="task-controls-link button--grey" href="{% url 'kanban:task_detail' task.id %}">к&nbsp;задаче</a>
                        </div>
                    {% endif %}
                </li>
            {% empty %}
                <li>нет активных задач</li>
            {% endfor %}
            </ol>
        </div>

        <div class="tasks-item task-completed">
            <h3 class="tasks-category-title">готовые задачи:</h3>
            <ol class="tasks-list">
            {% for task in tasks_completed %}
                <li>
                    <h4>{{ task.name }}</h4>
                    <p class="task-info">
                        <strong>исполнитель:</strong> {{ task.executor }}<br>
                        <strong>завершено:</strong> {{ task.completed_date }} в {{ task.completed_time }}
                    </p>
                    <p class="task-description">
                        {{ task.description|truncatechars:100 }}
                    </p>
                    {% if object.owner == user %}
                    <div class="task-controls">
                        <a class="task-controls-link button--grey" href="{% url 'kanban:task_detail' task.id %}">к&nbsp;задаче</a>
                        <a class="task-controls-link button--red" href="{% url 'kanban:task_delete' task.id %}">удалить</a>
                    </div>
                    {% endif %}
                </li>
            {% empty %}
                <li>нет готовых задач</li>
            {% endfor %}
            </ol>
        </div>

        <div class="tasks-item task-overdue">
            <h3 class="tasks-category-title">просроченные задачи:</h3>
            <ol class="tasks-list">
            {% for task in tasks_overdue %}
            <li>
                <h4>{{ task.name }}</h4>
                <p class="task-info">
                    <strong>исполнитель:</strong> {{ task.executor }}<br>
                    <strong>дедлайн:</strong> {{ task.deadline_date }} в {{ task.deadline_time }}
                </p>
                <p class="task-description">
                    {{ task.description|truncatechars:100 }}
                </p>
                {% if object.owner == user %}
                <div class="task-controls">
                    <a class="task-controls-link button--grey" href="{% url 'kanban:task_detail' task.id %}">к&nbsp;задаче</a>
                    <a class="task-controls-link button--red" href="{% url 'kanban:task_delete' task.id %}">удалить</a>
                </div>
                {% endif %}
            </li>
            {% empty %}
                <li>нет просроченных задач</li>
            {% endfor %}
            </ol>
        </div>
    </div>
    {% if object.owner == user %}
    <div class="page-controls">
        <a class="link-button" href="{% url 'kanban:task_create' kanban.id %}">добавить задачу</a>
        <a class="link-button button--red" href="{% url 'kanban:kanban_delete' kanban.id %}">удалить эту доску</a>
        <a class="link-button" href="{% url 'kanban:kanban_create' %}">создать новую доску</a>
        <a class="link-button" href="{% url 'kanban:index' %}">все доски</a>
    </div>
    {% endif %}
{% endblock %}

templates/kanban/login.html
{% extends "kanban/base.html" %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="войти">
</form>
{% endblock %}

templates/kanban/task_cancel.html
{% extends "kanban/base.html" %}

{% block content %}
    <div class="main-item">
        <h2>Отменить задачу</h2>
        <form class="task-form" action="" method="POST">
            {% csrf_token %}
            <p>Отменить {{ object.name }} для {{ object.executor.username }}?<br>Задача вернется в новые</p>
            <input class="form-button" type="submit" value="отменить задачу">
        </form>
        <p><a class="link-button" href="{% url 'kanban:kanban_detail' pk=task.kanban.pk %}">вернуться на доску</a></p>
    </div>
{% endblock %}

templates/kanban/task_complete.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="main-item">
    <form class="task-form" action="" method="POST">
        {% csrf_token %}
        <h2>Завершить задачу {{ object.name }}?</h2>
        <p>Это действие нельзя будет отменить!</p>
        {{ form.as_p }}
        <input class="form-button button--green" type="submit" value="завершить задачу">
    </form>
    <p><a class="link-button" href="{% url 'kanban:kanban_detail' pk=task.kanban.pk %}">вернуться на доску</a></p>
</div>
{% endblock %}

templates/kanban/task_create.html
{% extends "kanban/base.html" %}

{% block content %}
    <div class="main-item">
        <form class="task-form" action="" method="POST">
            <h2>Добавить задачу</h2>
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-button" type="submit" value="добавить задачу">
        </form>
        <p>
            <a class="link-button" href="{% url 'kanban:index' %}">на главную</a>
        </p>
    </div>
{% endblock %}

templates/kanban/task_delete.html
{% extends "kanban/base.html" %}

{% block content %}
    <div class="main-item">
        <h2>Удалить задачу</h2>
        <form class="task-form" action="" method="POST">
            {% csrf_token %}
            <p>Удалить задачу {{ object }}?</p>
            <input class="form-button button--red" type="submit" value="удалить задачу">
        </form>
        <p>
            <a class="link-button" href="{% url 'kanban:kanban_detail' pk=task.kanban.pk %}">вернуться на доску</a>
        </p>
    </div>
{% endblock %}

templates/kanban/task_detail.html
{% extends "kanban/base.html" %}

{% block content %}
    <div class="main-item">
        <h2 class="task-title">{{ task.name }}</h2>
        <div class="task-info">
            <p><strong>принадлежит доске:</strong> <a href="{% url 'kanban:kanban_detail' pk=task.kanban.pk %}">{{ task.kanban.name }}</a></p>
            <p><strong>статус:</strong> {{ task.get_status_display }}</p>
            
            <p><strong>создана:</strong> {{ task.created_date }} в {{ task.created_time }}</p>

            {% if task.assigned_date %}
                <p><strong>назначена:</strong> {{ task.assigned_date }} в {{ task.assigned_time }} пользователю {{ task.executor }}
                <p><strong>дедлайн:</strong> {{ task.deadline_date }} в {{ task.deadline_time }}</p>
            {% endif %}

            {% if task.completed_date %}
                <p><strong>завершена:</strong> {{ task.completed_date }} в {{ task.completed_time }}</p>
            {% endif %}
        </div>

        <div class="task-description">
            {{ task.description }}
        </div>

        <div class="page-controls">
        {% if request.user == task.kanban.owner %}
            {% if task.status == "new"%}
                <a class="link-button button--yellow" href="{% url 'kanban:task_activate' pk=task.pk %}">назначить&nbsp;задачу</a>
            {% endif %}

            {% if task.status == "active"%}
                <a class="link-button button--green" href="{% url 'kanban:task_complete' pk=task.pk %}">завершить&nbsp;задачу</a>
                <a class="link-button" href="{% url 'kanban:task_cancel' pk=task.pk %}">отменить&nbsp;задачу</a>
            {% endif %}

            {% if task.status == "overdue"%}
                <a class="link-button" href="{% url 'kanban:task_cancel' pk=task.pk %}">отменить&nbsp;задачу</a>
            {% endif %}

            <a class="link-button button--red" href="{% url 'kanban:task_delete' pk=task.pk %}">удалить&nbsp;задачу</a>

        {% endif %}
        <a class="link-button" href="{% url 'kanban:kanban_detail' pk=task.kanban.pk %}">вернуться&nbsp;на&nbsp;доску</a>
        </div>
    </div>

{% endblock %}

templates/kanban/user_signup.html
{% extends "kanban/base.html" %}

{% block content %}
    <div class="main-item">
        <h2>Зарегистрироваться</h2>
        <form class="task-form" action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-button" type="submit" value="зарегистрироваться">
        </form>
    </div>
{% endblock %}